package gui2d;

/**
 * Enumerates the different states the gui is in.
 * 
 * @author Michael
 *
 */
public enum GUI2DMode {
	START, LOBBY, DECK_EDIT, INGAME, BOT_CHOOSER, ARENA_CHOOSE_LOBBY, MAMORIA_CITY_ARENA, AZURIA_CITY_ARENA, ORANIA_CITY_ARENA, PRISMANIA_CITY_ARENA, FUCHSANIA_CITY_ARENA, SAFFRONIA_CITY_ARENA, ZINNOBERINSEL_ARENA, VERTANIA_CITY_ARENA;
}
