package arenaMode.model;

public enum ArenaFighterCode {
	MAMORIA_RED, MAMORIA_BRENDAN, MAMORIA_BROCK, AZURIA_LYRA, AZURIA_MAY, AZURIA_MISTY, ORANIA_LEAF, ORANIA_NATE, ORANIA_LTSURGE, PRISMANIA_ROSA, PRISMANIA_SERENA, PRISMANIA_ERIKA, FUCHSANIA_HILBERT, FUCHSANIA_LUCAS, FUCHSANIA_KOGA, SAFFRONIA_HILDA, SAFFRONIA_CALEM, SAFFRONIA_SABRINA, ZINNOBER_ETHAN, ZINNOBER_DAWN, ZINNOBER_PYRO, VERTANIA_ROCKET_FEMALE, VERTANIA_ROCKET_MALE, VERTANIA_GIOVANNI;
}
