package model.enums;

public enum PlayerAction {
	SHOW_CARDS_ON_POSITION, PLAY_TRAINER_CARD, PLAY_ENERGY_CARD, PUT_ON_BENCH, EVOLVE_POKEMON, ATTACK_1, ATTACK_2, POKEMON_POWER, RETREAT_POKEMON, ACTIVATE_STADIUM_EFFECT;
}
